<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-09-07T20:01:31 EET" name="Suite" finished-at="2021-09-07T20:01:31 EET" duration-ms="173">
    <groups>
    </groups>
    <test started-at="2021-09-07T20:01:31 EET" name="Test" finished-at="2021-09-07T20:01:31 EET" duration-ms="173">
      <class name="com.Calculator.test.TestCases">
        <test-method signature="divTest()[pri:0, instance:com.Calculator.test.TestCases@524d6d96]" started-at="2021-09-07T20:01:31 EET" name="divTest" finished-at="2021-09-07T20:01:31 EET" duration-ms="20" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divTest -->
        <test-method signature="multTest()[pri:0, instance:com.Calculator.test.TestCases@524d6d96]" started-at="2021-09-07T20:01:31 EET" name="multTest" finished-at="2021-09-07T20:01:31 EET" duration-ms="5" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[error in mult function expected [8] but found [6]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: error in mult function expected [8] but found [6]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at com.Calculator.test.TestCases.multTest(TestCases.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- multTest -->
        <test-method signature="subTest()[pri:0, instance:com.Calculator.test.TestCases@524d6d96]" started-at="2021-09-07T20:01:31 EET" name="subTest" finished-at="2021-09-07T20:01:31 EET" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- subTest -->
        <test-method signature="sumTest()[pri:0, instance:com.Calculator.test.TestCases@524d6d96]" started-at="2021-09-07T20:01:31 EET" name="sumTest" finished-at="2021-09-07T20:01:31 EET" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sumTest -->
      </class> <!-- com.Calculator.test.TestCases -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
